import { useState, useRef, useEffect, useCallback } from "react";
import { motion, AnimatePresence, useInView } from "motion/react";

export default function WhyMads() {
    const [activeTab, setActiveTab] = useState(0);

    const sectionRef = useRef(null);
    const tableRef = useRef(null);
    const lineRefs = useRef([]);
    const isInView = useInView(sectionRef, { amount: 0.3 });
    const [borderPath, setBorderPath] = useState('');
    const [lineY, setLineY] = useState(0);

    const tables = [
        {
            id: 0,
            title: "Why MADS?",
            headers: ["Benefits", "Features"],
            layout: "checklist",
            arrowY: 15,
            data: [
                { col1: "✔️ Guaranteed Results", col2: "✔️ 3× Growth in 3 Months" },
                { col1: "✔️ Regular Posting", col2: "✔️ Stay in audience eyes" },
                { col1: "✔️ Viral Content", col2: "✔️ Massive Reach" },
                { col1: "✔️ Cohesive Identity Across Platforms", col2: "✔️ Trusted Brand" },
                { col1: "✔️ Latest Trend", col2: "✔️ Win over Competitors" },
                { col1: "✔️ Regular Reports", col2: "✔️ Clear Progress Tracking" },
                { col1: "✔️ Posting With Purpose", col2: "✔️ Leads & Conversions Boost" }
            ]
        },
        {
            id: 1,
            title: "How to measure MADS Effectiveness",

            layout: "description",
            arrowY: 52,
            description:
                "Evaluating the success of your SMM program is not always straightforward. To measure their effectiveness, it's important to look at both quantitative and qualitative metrics. Quantitative measures can be tracked easily with analytics tools, giving you an objective measure of success. Here are some examples of how we track the success of our SMM services:",
            data: [
                { col1: "Lead generation", col2: "The number of new leads generated through posting efforts" },
                { col1: "Conversion rate", col2: "The percentage of leads that turn into customers" },
                { col1: "Customer acquisition cost", col2: "The total cost of marketing efforts divided by the number of new customers acquired" },
                { col1: "Return on marketing investment (ROMI)", col2: "The revenue generated from marketing efforts divided by your B2B marketing investments" },
                { col1: "Customer lifetime value (CLV)", col2: "The estimated total revenue generated by a customer during their relationship with the company" }
            ]
        },
        {
            id: 2,
            title: "Our Subscription-Based SMM Workflow Strategy, Design & Results in One Package",

            layout: "description",
            arrowY: 96,
            description:
                "We don't just post — we build social strategies that grow your brand. Our SMM process blends strategy, audience insights, and platform expertise to deliver campaigns that engage and convert.",
            workflowSubtitle: "Here's what your journey with us looks like:",
            data: [
                { col1: "Deep Discovery", col2: "We learn your brand and audit your presence. We dive into your business goals and review your current social media or help you build from scratch if you're starting fresh." },
                { col1: "Custom Strategy", col2: "We build a plan aligned with your goals. We select the right channels, craft your content approach, and create a clear roadmap for growth." },
                { col1: "Smart Execution", col2: "We launch creative campaigns that perform. Our team produces, publishes, and promotes content both organic and paid to drive real engagement." },
                { col1: "Performance Tracking", col2: "We measure what matters and optimize fast. You get clear reports, data-driven insights, and ongoing tweaks that keep results moving in the right direction." },
                { col1: "Ongoing Management", col2: "Less oversight, more impact. Our team keeps your social channels active, aligned, and growing without pulling your time into daily details." }
            ]
        }
    ];

    const handleTabClick = (index) => {
        if (index === activeTab) return;
        setBorderPath('');
        setActiveTab(index);
    };

    const premiumEase = [0.22, 1, 0.36, 1];

    useEffect(() => {
        if (!isInView) {
            setActiveTab(0);
            setBorderPath('');
        }
    }, [isInView]);

    // Build SVG path starting from arrowY% on the left edge, going clockwise
    const buildPath = useCallback((W, H, startYPct) => {
        const r = 11, s = 1;
        const sy = s + (H - 2 * s) * (Math.min(startYPct, 94) / 100);
        return [
            `M ${s} ${sy}`,
            `L ${s} ${r + s}`,
            `Q ${s} ${s} ${r + s} ${s}`,
            `L ${W - r - s} ${s}`,
            `Q ${W - s} ${s} ${W - s} ${r + s}`,
            `L ${W - s} ${H - r - s}`,
            `Q ${W - s} ${H - s} ${W - r - s} ${H - s}`,
            `L ${r + s} ${H - s}`,
            `Q ${s} ${H - s} ${s} ${H - r - s}`,
            `L ${s} ${sy}`,
        ].join(' ');
    }, []);

    useEffect(() => {
        if (!tableRef.current) return;
        // Measure AFTER the 0.7s line animation finishes reaching the table
        const t = setTimeout(() => {
            const tableRect = tableRef.current?.getBoundingClientRect();
            const lineEl = lineRefs.current[activeTab];
            if (!tableRect || !lineEl) return;
            const lineRect = lineEl.getBoundingClientRect();
            const lineCenterY = lineRect.top + lineRect.height / 2;
            const yOffset = lineCenterY - tableRect.top;
            const yPct = Math.max(0, Math.min((yOffset / tableRect.height) * 100, 94));
            setLineY(yPct);
            setBorderPath(buildPath(tableRect.width, tableRect.height, yPct));
        }, 720); // slightly after the 0.7s line animation
        return () => clearTimeout(t);
    }, [activeTab, isInView, buildPath]);

    // Also update path on resize without the delay
    useEffect(() => {
        if (!tableRef.current) return;
        const ro = new ResizeObserver(() => {
            const tableRect = tableRef.current?.getBoundingClientRect();
            if (tableRect) setBorderPath(buildPath(tableRect.width, tableRect.height, lineY));
        });
        ro.observe(tableRef.current);
        return () => ro.disconnect();
    }, [lineY, buildPath]);

    return (
        <section ref={sectionRef} className="relative z-0 bg-[white] min-h-screen flex items-center py-20 overflow-hidden">
            <style>{`
                @keyframes drawBorder { from { stroke-dashoffset: 1; } to { stroke-dashoffset: 0; } }
                @keyframes revealContent { 
                    from { clip-path: inset(0 0 100% 0); -webkit-clip-path: inset(0 0 100% 0); } 
                    to { clip-path: inset(0 0 0% 0); -webkit-clip-path: inset(0 0 0% 0); } 
                }
            `}</style>




            <div className="max-w-6xl mx-auto px-6 flex flex-col lg:flex-row gap-16 items-start relative z-10">


                <div className="lg:w-[344px] space-y-12 w-full relative">
                    {tables.map((table, index) => (
                        <div key={table.id} onClick={() => handleTabClick(index)} className="group cursor-pointer relative">

                            <h2 className={`font-medium mb-6 leading-tight tracking-tight transition-all duration-700
                                ${activeTab === index
                                    ? "text-black opacity-100 scale-100"
                                    : "text-black opacity-40 hover:opacity-60 scale-[0.98]"}
                                ${index === 0 ? "text-[38px] leading-[42px]" : "text-[20px] leading-[28px]"}`}
                            >
                                {table.title}
                            </h2>

                            <div
                                ref={el => lineRefs.current[index] = el}
                                className="relative h-6 flex items-center overflow-visible"
                            >
                                <motion.div
                                    initial={false}
                                    animate={{
                                        width: activeTab === index ? "calc(100% + 4.1rem)" : "48px",
                                        backgroundColor: activeTab === index ? "#000" : "rgba(0,0,0,0.15)"
                                    }}
                                    transition={{ duration: 0.7, ease: premiumEase }}
                                    className="absolute left-0 h-[1.5px] z-20 origin-left"
                                />

                                {activeTab !== index && (
                                    <div className="absolute left-[48px] top-1/2 -translate-y-1/2">
                                        <svg width="14" height="14" viewBox="0 0 24 24">
                                            <path d="M5 12H19M19 12L12 5M19 12L12 19"
                                                stroke="black" strokeWidth="2.5" fill="none" />
                                        </svg>
                                    </div>
                                )}
                            </div>

                            {/* MOBILE ACCORDION CONTENT */}
                            <AnimatePresence>
                                {activeTab === index && (
                                    <motion.div
                                        initial={{ opacity: 0, height: 0 }}
                                        animate={{ opacity: 1, height: "auto" }}
                                        exit={{ opacity: 0, height: 0 }}
                                        transition={{ duration: 0.3 }}
                                        className="lg:hidden mt-8 overflow-hidden"
                                    >
                                        <div className="relative rounded-[12px] bg-white/40 shadow-[0_4px_30px_rgba(0,0,0,0.02)] overflow-hidden">

                                            {/* Rounded animated border via SVG - fading lead */}
                                            <svg className="absolute inset-0 w-full h-full pointer-events-none z-30" style={{ overflow: 'visible' }}>
                                                {[
                                                    { o: 0.15, d: '0s' },
                                                    { o: 0.35, d: '0.08s' },
                                                    { o: 0.65, d: '0.16s' },
                                                    { o: 1, d: '0.24s' },
                                                ].map((layer, i) => (
                                                    <rect
                                                        key={i}
                                                        x="1" y="1" width="calc(100% - 2px)" height="calc(100% - 2px)"
                                                        rx="11" ry="11" fill="none" stroke="black" strokeWidth="1.5"
                                                        pathLength="1" strokeDasharray="1"
                                                        style={{
                                                            strokeDashoffset: 1,
                                                            opacity: layer.o,
                                                            animation: `drawBorder 1.5s ease-out ${layer.d} forwards`
                                                        }}
                                                    />
                                                ))}
                                            </svg>

                                            {/* Content */}
                                            <div
                                                className="flex flex-col relative z-0"
                                                style={{
                                                    clipPath: 'inset(0 0 100% 0)',
                                                    WebkitClipPath: 'inset(0 0 100% 0)',
                                                    animation: `revealContent 1.5s ease-out forwards`
                                                }}
                                            >
                                                {table.headers && (
                                                    <div className="grid grid-cols-2 border-b border-black/[0.08]">
                                                        {table.headers.map((h, i) => (
                                                            <div key={i} className={`p-6 text-center text-lg font-bold ${i === 0 ? "border-r border-black/[0.08]" : ""}`}>
                                                                {h}
                                                            </div>
                                                        ))}
                                                    </div>
                                                )}

                                                {table.description && (
                                                    <div className="p-8 pb-6 text-[13px] leading-[20px] text-black/80">
                                                        {table.description}
                                                    </div>
                                                )}

                                                <div className="mx-8 h-[1px] bg-black/[0.08]" />

                                                <div className="px-8 py-4">
                                                    {table.data.map((item, idx) => (
                                                        <div
                                                            key={idx}
                                                            className="grid grid-cols-2 border-b last:border-0 border-black/[0.04] py-3"
                                                        >
                                                            <div className="font-bold text-[14px]">{item.col1}</div>
                                                            <div className="text-[12.5px] text-black/60">{item.col2}</div>
                                                        </div>
                                                    ))}
                                                </div>
                                            </div>
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>

                            {index < tables.length - 1 && (
                                <div className="w-full h-[1px] bg-black/[0.08] mt-12" />
                            )}
                        </div>
                    ))}
                </div>

                {/* RIGHT SIDE TABLE - Desktop Only */}
                <div className="hidden bg-white/20 lg:block lg:w-[696px] w-full relative pt-2">

                    <AnimatePresence mode="wait">
                        <motion.div
                            key={activeTab}
                            initial={{ opacity: 0, scale: 0.98 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0, scale: 0.98 }}
                            transition={{ duration: 0.25 }}
                        >
                            <div ref={tableRef} className="relative rounded-[12px] bg-white/40 shadow-[0_4px_30px_rgba(0,0,0,0.02)] overflow-hidden">

                                {/* Border draws from where the title line connects — multi-layer faded head */}
                                {borderPath && (
                                    <svg
                                        key={`border-${activeTab}-${isInView}`}
                                        className="absolute inset-0 w-full h-full pointer-events-none z-30"
                                    >
                                        {[
                                            { o: 0.15, d: '0s' },
                                            { o: 0.35, d: '0.08s' },
                                            { o: 0.65, d: '0.16s' },
                                            { o: 1, d: '0.24s' },
                                        ].map((layer, i) => (
                                            <path
                                                key={i}
                                                d={borderPath}
                                                fill="none" stroke="black" strokeWidth="1.5"
                                                pathLength="1" strokeDasharray="1"
                                                style={{
                                                    strokeDashoffset: 1,
                                                    opacity: layer.o,
                                                    animation: `drawBorder 1.5s ease-out ${layer.d} forwards`
                                                }}
                                            />
                                        ))}
                                    </svg>
                                )}

                                {/* ✅ TABLE CONTENT — NOT MODIFIED */}
                                <div
                                    className="flex flex-col relative z-0"
                                    style={{
                                        clipPath: 'inset(0 0 100% 0)',
                                        WebkitClipPath: 'inset(0 0 100% 0)',
                                        animation: borderPath ? `revealContent 1.5s ease-out forwards` : 'none',
                                        opacity: borderPath ? 1 : 0
                                    }}
                                >

                                    {tables[activeTab].headers && (
                                        <div className="grid grid-cols-2 border-b border-black/[0.08]">
                                            {tables[activeTab].headers.map((h, i) => (
                                                <div key={i}
                                                    className={`p-6 md:p-8 text-center text-lg font-bold ${i === 0 ? "border-r border-black/[0.08]" : ""}`}>
                                                    {h}
                                                </div>
                                            ))}
                                        </div>
                                    )}

                                    {tables[activeTab].description && (
                                        <div className="p-8 md:p-10 pb-6 text-[13px] leading-[20px] text-black/80">
                                            {tables[activeTab].description}
                                        </div>
                                    )}

                                    <div className="mx-8 md:mx-10 h-[1px] bg-black/[0.08]" />

                                    <div className="px-8 md:px-10 py-4">
                                        {tables[activeTab].data.map((item, idx) => (
                                            <div
                                                key={idx}
                                                className="grid grid-cols-2 border-b last:border-0 border-black/[0.04] py-3"
                                            >
                                                <div className="font-bold text-[14px]">{item.col1}</div>
                                                <div className="text-[12.5px] text-black/60">{item.col2}</div>
                                            </div>
                                        ))}
                                    </div>

                                </div>
                            </div>
                        </motion.div>
                    </AnimatePresence>
                </div>
            </div>
        </section>
    );
}
